SERVER_ADDRESS = '127.0.0.1'
SERVER_PORT = 12000
SERVER = (SERVER_ADDRESS, SERVER_PORT)

PACKET_SIZE = 1024
PACKET_SEND_REPEAT_COUNT = 2

BOARD_WIDTH = 960
BOARD_HEIGHT = BOARD_WIDTH

PLAYER_START_X = BOARD_WIDTH / 2
PLAYER_START_Y = BOARD_HEIGHT - 60
