SERVER_ADDRESS = '127.0.0.1'
SERVER_PORT = 12000
SERVER = (SERVER_ADDRESS, SERVER_PORT)

PACKET_SIZE = 1024
PACKET_SEND_REPEAT_COUNT = 2

WINDOW_WIDTH = 960
WINDOW_HEIGHT = WINDOW_WIDTH

# TODO remove magic number 1595 (stands for board.png height)
SCALE = WINDOW_HEIGHT / 1595

# TODO remove magic number 60
STRIKER_START_X = WINDOW_WIDTH / 2
PLAYER_STRIKER_START_Y = WINDOW_HEIGHT - 60
ENEMY_STRIKER_START_Y = 60
