WINDOW_WIDTH = 960
WINDOW_HEIGHT = WINDOW_WIDTH
WINDOW_TITLE = "Air Hockey"
TARGET_FPS = 60
SCALE = WINDOW_HEIGHT/1595

ASSETS_FOLDER = "assets/"

SERVER_ADDRESS = '127.0.0.1'
SERVER_PORT = 12000
SERVER = (SERVER_ADDRESS, SERVER_PORT)
PACKET_SIZE = 1024
REQUEST_TIMEOUT = 1.0
