WINDOW_WIDTH = 960
WINDOW_HEIGHT = WINDOW_WIDTH
WINDOW_TITLE = "Air Hockey"
TARGET_FPS = 60

ASSETS_FOLDER = "src/client/assets/"
REQUEST_TIMEOUT = 1.0

SCALE = WINDOW_HEIGHT/1595
STRIKERS_NUMBER = 2
